name: active_memory
description: "활쓴당"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0' # Dart 3.0 이상 필수 (Record, Pattern Matching 사용 위해)

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  dio: ^5.7.0
  retrofit: ^4.4.1

  freezed_annotation: ^2.4.4 # data class & 불변 객체
  json_annotation: ^4.9.0

  go_router: ^14.6.0

  flutter_secure_storage: ^9.2.2 # JWT Access Token 저장용
  shared_preferences: ^2.3.2 # 테마등 간단할 설정 저장용

  intl: ^0.19.0
  flutter_dotenv: ^6.0.0
  kakao_flutter_sdk_user: ^1.9.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3
  freezed: ^2.5.7
  
  json_serializable: ^6.9.0
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true
  assets:
    - .env.dev
    - .env.prod
